version: '3.5'

services:
  skopeo:
    image: exfly/skopeo:alpine
    command: tail -f /dev/null
    container_name: skopeo.local
    hostname: skopeo.local
    volumes:
      - .:/output
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - selfhostsrv
    restart: unless-stopped

networks:
  selfhostsrv:
    driver: bridge
    name: selfhostsrv
