FROM alpine:3.10
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
# ADD someCA.pem /usr/local/share/ca-certificates/some-ca.crt
# RUN apk add --no-cache ca-certificates && update-ca-certificates
