version: '3.5'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger.local
    hostname: jaeger.local
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    restart: unless-stopped

networks:
  default:
    external:
      name: selfhostsrv
